version: "3.8"
services:
    mongodb:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        networks:
            - idp_network
            - db_network
        volumes:
            - mongo_data:/data/db
    
    script:
        image: "radubreazu/idp:script"
        depends_on:
            - mongodb
        ports:
            - "6000:6000"
        networks:
            - idp_network
        environment:
            MONGO_URI: mongodb://mongodb:27017/Users
        stdin_open: false
        tty: false    
    
    dbms:
        image: mongo-express
        depends_on:
            - mongodb
        ports:
            - "8081:8081"
        networks:
            - db_network
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    
    auth:
        image: "radubreazu/idp:authentication"
        depends_on:
            - script
            - interpreter
        networks:
            - idp_network
        ports:
            - "5001:5001"
        stdin_open: true
        tty: true
    
    interpreter:
        build:
            context: ../interpreter
            dockerfile: Dockerfile
        depends_on:
            - mongodb
        ports:
            - "8001:8001"
        networks:
            - idp_network
        stdin_open: false
        tty: false

    kong:
        image: radubreazu/idp:kong
        environment:
            KONG_DATABASE: 'off' # obligatoriu, dacă se vrea modul DB-less
            KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml # trebuie specificat unde anume se va găsi fișierul de configurare
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8005, 0.0.0.0:8448 ssl
        ports:
            - "80:8000"  # Kong proxy port
            - "443:8443"  # Kong proxy SSL port
            - "8005:8005"  # Kong admin port
            - "8448:8448"  # Kong admin SSL port
        networks:
            - idp_network

networks:
    idp_network:
        driver: bridge
    db_network:
        driver: bridge

volumes:
    mongo_data: {}    